//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteca_rest_service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_lector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_lector()
        {
            this.t_prestamo = new HashSet<t_prestamo>();
        }
    
        public int id_lector { get; set; }
        public string nu_dni { get; set; }
        public string tx_nombres { get; set; }
        public string tx_direccion { get; set; }
        public Nullable<System.DateTime> dt_fecha_nac { get; set; }
        public Nullable<int> nu_estado { get; set; }
        public string tx_email { get; set; }
        public string tx_contrasena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_prestamo> t_prestamo { get; set; }
    }
}
