//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteca_rest_service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_prestamo
    {
        public int id_prestamo { get; set; }
        public System.DateTime dt_fecha_prestamo { get; set; }
        public string nu_dni { get; set; }
        public string tx_cod_bibl { get; set; }
        public System.DateTime dt_fecha_vencimiento { get; set; }
        public Nullable<int> nu_estado { get; set; }
        public Nullable<System.DateTime> dt_fecha_devolucion { get; set; }
    
        public virtual t_catalogo t_catalogo { get; set; }
        public virtual t_lector t_lector { get; set; }
    }
}
